INSERT INTO USER (ID, ACTIVE, PASSWORD, PASSWORD_CONFIRM, ROLE, USER_NAME)
VALUES (1, true, 1234, 1234, 'admin', 'faker');

INSERT INTO USER (ID, ACTIVE, PASSWORD, PASSWORD_CONFIRM, ROLE, USER_NAME)
VALUES (2, true, 1234, 1234, 'admin', 'madlife');

INSERT INTO USER (ID, ACTIVE, PASSWORD, PASSWORD_CONFIRM, ROLE, USER_NAME)
VALUES (3, true, 1234, 1234, 'admin', 'showmaker');